// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScrapWars.Infrastructure.Persistence;

#nullable disable

namespace ScrapWars.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScrapWarsDbContext))]
    partial class ScrapWarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScrapWars.Domain.Entities.CategoryNotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("IX_category_notification_channels_guild_id");

                    b.HasIndex("CategoryId", "ChannelId")
                        .IsUnique()
                        .HasDatabaseName("UX_category_notification_channels_category_id_channel_id");

                    b.ToTable("category_notification_channels", (string)null);
                });

            modelBuilder.Entity("ScrapWars.Domain.Entities.GuildSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<int>("ExtraCategories")
                        .HasColumnType("integer")
                        .HasColumnName("extra_categories");

                    b.Property<decimal>("ExtraCategoryUnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("extra_category_unit_price");

                    b.Property<decimal>("ExtraChannelUnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("extra_channel_unit_price");

                    b.Property<int>("ExtraChannels")
                        .HasColumnType("integer")
                        .HasColumnName("extra_channels");

                    b.Property<decimal>("ExtraProductUnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("extra_product_unit_price");

                    b.Property<int>("ExtraProducts")
                        .HasColumnType("integer")
                        .HasColumnName("extra_products");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("UX_guild_subscriptions_guild_id");

                    b.ToTable("guild_subscriptions", (string)null);
                });

            modelBuilder.Entity("ScrapWars.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_products_category_id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("IX_products_guild_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ScrapWars.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("IX_product_categories_guild_id");

                    b.HasIndex("GuildId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_product_categories_guild_id_normalized_name");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("ScrapWars.Domain.Entities.CategoryNotificationChannel", b =>
                {
                    b.HasOne("ScrapWars.Domain.Entities.ProductCategory", "Category")
                        .WithMany("NotificationChannels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScrapWars.Domain.Entities.Product", b =>
                {
                    b.HasOne("ScrapWars.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScrapWars.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("NotificationChannels");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
